### ISSUE TITLE
Bug, can't connect and retrieve the data

### ISSUE THREAD

**Issue by skyluker** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#11]
Hi,

For few weeks now an error has occured and the component has stopped working.

Logger: homeassistant.components.sensor
Source: custom_components/tauron_amiplus/sensor.py:72
Integration: Sensor (documentation, issues)
First occurred: February 11, 2021, 6:23:47 PM (1 occurrences)
Last logged: February 11, 2021, 6:23:47 PM

Error while setting up tauron_amiplus platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xacdb70d0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='logowanie.tauron-dystrybucja.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xacdb70d0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 61, in setup_platform
    dev.append(TauronAmiplusSensor(name, username, password, meter_id, generation, variable))
  File "/config/custom_components/tauron_amiplus/sensor.py", line 123, in __init__
    configuration = calculate_configuration(username, password, meter_id)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 72, in calculate_configuration
    session.request("POST", TauronAmiplusSensor.url_login, data=payload_login,
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='logowanie.tauron-dystrybucja.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xacdb70d0>: Failed to establish a new connection: [Errno -3] Try again'))

No configuration was changed by me to provoke it.

**Comment by PiotrMachowski** [comment]
Does everything work on elicznik website?

**Comment by skyluker** [comment]
> Does everything work on elicznik website?

Yes.

But I noticed my licznik_id has been changed somehow on a website. After updating the number in HA the component works again. Sorry to bother you, thanks for you work!
