### ISSUE TITLE
HA 2023.3.1 NoneType' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by bazwro** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#120]
Witam,
od dłuższego czasu nie działało (miałem starszą wersje HA, integracja nie chciała się z oczywistych względów zaaktualizować), wczoraj zabrałem sie za gruntowne aktualizacje, niestety nie mam pomysłów już co z problemem zrobić.

Home Assistant 2023.3.1
![image](https://user-images.githubusercontent.com/129499970/229081008-7b0e8acf-0eb8-4141-8c0f-80a24c368410.png)
![image](https://user-images.githubusercontent.com/129499970/229077595-d4c7b951-53ae-4f2c-80a7-4d40c47d0aa5.png)
![image](https://user-images.githubusercontent.com/129499970/229077774-d4af4b36-76bf-426d-afce-a4281190ff67.png)

```
Ten błąd pochodzi z niestandardowej integracji.

Logger: aiohttp.server
Source: custom_components/tauron_amiplus/connector.py:254
Integration: Tauron AMIplus (documentation, issues)
First occurred: 10:23:34 (2 occurrences)
Last logged: 10:55:26

Error handling request
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/homeassistant/components/diagnostics/__init__.py", line 246, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
  File "/data/data/com.termux/files/home/AIS/custom_components/tauron_amiplus/diagnostics.py", line 14, in async_get_config_entry_diagnostics
    return await hass.async_add_executor_job(get_config_entry_diagnostics, entry)
  File "/data/data/com.termux/files/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/data/com.termux/files/home/AIS/custom_components/tauron_amiplus/diagnostics.py", line 30, in get_config_entry_diagnostics
    raw_data = connector.get_raw_data()
  File "/data/data/com.termux/files/home/AIS/custom_components/tauron_amiplus/connector.py", line 103, in get_raw_data
    data.consumption = self.get_data_set(generation=False)
  File "/data/data/com.termux/files/home/AIS/custom_components/tauron_amiplus/connector.py", line 125, in get_data_set
    dataset.json_configurable_hourly = self.get_raw_values_daily_for_range(start, end, generation)
  File "/data/data/com.termux/files/home/AIS/custom_components/tauron_amiplus/connector.py", line 219, in get_raw_values_daily_for_range
    "from": TauronAmiplusConnector.format_date(day_from),
  File "/data/data/com.termux/files/home/AIS/custom_components/tauron_amiplus/connector.py", line 254, in format_date
    return date.strftime(CONST_DATE_FORMAT)
AttributeError: 'NoneType' object has no attribute 'strftime'

```

**Comment by PiotrMachowski** [comment]
@bazwro zadziałało jednak?

**Comment by bazwro** [comment]
@PiotrMachowski usunąłem całą integrację i konfigurację, kilka restartów, ponowna instalacja i konfiguracja i poszło.
