### ISSUE TITLE
Balanced sensors do not work in G11 tariff

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#129]
```
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.tauron_amiplus.coordinator
Source: custom_components/tauron_amiplus/sensor.py:233 
Integration: Tauron AMIplus (documentation, issues) 
First occurred: 18:22:53 (2 occurrences) 
Last logged: 20:11:14

Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.tauron_amiplus.coordinator.TauronAmiplusUpdateCoordinator object at 0x7f6b21dc30>>
Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.tauron_amiplus.coordinator.TauronAmiplusUpdateCoordinator object at 0x7f6838a410>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 111, in _handle_timer_finish
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 226, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 341, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
    update_callback()
  File "/config/custom_components/tauron_amiplus/sensor.py", line 154, in _handle_coordinator_update
    self.update_balanced_data(data.balance_daily, data.tariff)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 193, in update_balanced_data
    balance, sum_consumption, sum_generation, zones, data_range = TauronAmiplusSensor.get_balanced_data(con, gen)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 233, in get_balanced_data
    zone = zone_names[consumption["Zone"]]
KeyError: 'cała doba'
```

**Comment by PiotrMachowski** [comment]
Fixed in `v2.4.10`
