### ISSUE TITLE
Some entities are unavailable

### ISSUE THREAD

**Issue by gstrzelecki** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#139]
Some of my entities are unavailable:

![image](https://user-images.githubusercontent.com/12390985/236643312-a26d5b29-35f4-4a8c-a1ac-fe8906cae520.png)

I've checked logs and found following errors:
(1)
Ten błąd pochodzi z niestandardowej integracji.

Logger: homeassistant
Source: custom_components/tauron_amiplus/sensor.py:233
Integration: Tauron AMIplus (documentation, issues)
First occurred: 16:57:58 (1 occurrences)
Last logged: 16:57:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 204, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/config/custom_components/tauron_amiplus/sensor.py", line 154, in _handle_coordinator_update
    self.update_balanced_data(data.balance_daily, data.tariff)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 193, in update_balanced_data
    balance, sum_consumption, sum_generation, zones, data_range = TauronAmiplusSensor.get_balanced_data(con, gen)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 233, in get_balanced_data
    zone = zone_names[consumption["Zone"]]
KeyError: 'cała doba'

(2)
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:267
Integration: Sensor (documentation, issues)
First occurred: 08:23:54 (1 occurrences)
Last logged: 08:23:54

Setup of platform tauron_amiplus is taking longer than 60 seconds. Startup will proceed without waiting any longer.

**Comment by gstrzelecki** [comment]
Sorry, I've missed that there are new versions. Checking this now!
