### ISSUE TITLE
Error while setting up tauron_amiplus platform for sensor

### ISSUE THREAD

**Issue by CaesarPL** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#14]
Since couple of days I'm receiving error as below when starting Home Assistant. It used to work perfectly and integration is very helpful in my case, thus I miss it :(

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 61, in setup_platform
    dev.append(TauronAmiplusSensor(name, username, password, meter_id, generation, variable))
  File "/config/custom_components/tauron_amiplus/sensor.py", line 123, in __init__
    configuration = calculate_configuration(username, password, meter_id)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 86, in calculate_configuration
    json_data = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by PiotrMachowski** [comment]
Please check if charts work on eLicznik website.

**Comment by CaesarPL** [comment]
Yes, they do without any issue. 

Jeżeli trzeba to możemy po polsku ;)

**Comment by PiotrMachowski** [comment]
A dane są dostępne (z "wczoraj")?

**Comment by CaesarPL** [comment]
Tak, jak najbardziej:
![image](https://user-images.githubusercontent.com/7214106/112679427-7413d100-8e6c-11eb-8089-13eece6c8fd7.png)

**Comment by PiotrMachowski** [comment]
U mnie od paru dni dane zniknęły na stronie, może znowu coś zmienili...

**Comment by PiotrMachowski** [comment]
@CaesarPL jednak działa?

**Comment by CaesarPL** [comment]
Zmieniłem hasło, wpisałem nowe do konfiguracji i magicznie zadziałało. Dziękuję bardzo za szybki odzew!

**Comment by PiotrMachowski** [comment]
Magicznie -> najlepiej ;)
