### ISSUE TITLE
Problem ze zmianą daty okresu podsumowań

### ISSUE THREAD

**Issue by nkdm01** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#196]
Cześć,

Podczas zmiany daty początku okresu wywala mi następujący błąd:
Dodam, że próbowałem już wyłączyć usługę odczekać 24h włączyć podejść do tematu ponownie ale nie efekt był ten sam

Oczywiście skutek jest taki że po próbie zmiany nie da się zalogować do eLicznika i jest info żeby spróbować za 8h, oraz restartuje się HA.

Czy macie jakiś pomysł jak sobie z tym poradzić?

Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.tauron_amiplus.coordinator
Źródło: helpers/update_coordinator.py:354
integracja: Tauron AMIplus (dokumentacja, Problemy)
Pierwsze zdarzenie: 15:06:30 (2 zdarzenia)
Ostatnio zalogowany: 15:06:41

Unexpected error fetching tauron_amiplus data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 35, in update_method
    data = await self.hass.async_add_executor_job(self._update)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 49, in _update
    return self.connector.get_raw_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/connector.py", line 120, in get_raw_data
    data.tariff = self.login()
                  ^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/connector.py", line 193, in login
    session, login_response = self.login_service(CONST_URL_LOGIN, CONST_URL_SERVICE)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/connector.py", line 183, in login_service
    raise Exception("Too many login attempts")
Exception: Too many login attempts

**Comment by PiotrMachowski** [comment]
Możliwe, że przy edycji HA nie lubi długiego czasu restartu integracji i próbuje wymusić ponowny restart powodując nadmiarowe próby logowania :/ Moja propozycja na workaround to najpierw wyłączenie integracji , a potem usunięcie i dodanie jej ponownie ze zmienioną konfiguracją. Dane historyczne powinny zostać zachowane

**Comment by nkdm01** [comment]
Dzięki za info tak spróbuje zrobić.

**Comment by jarekb76** [comment]
Potwierdzam że taki problem wystepuje. Spróbuje zaproponowanego obejścia jak tyko elicznik ponownie pozwoli mi sie logować

**Comment by PiotrMachowski** [comment]
Fixed in [v2.7.0](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.7.0)
