### ISSUE TITLE
KeyError: 'dane'

### ISSUE THREAD

**Issue by Nizm0** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#3]
Hi

I just noticed this error, I'm not sure when it first appeared.

2019-12-08 21:17:34 ERROR (MainThread) [homeassistant.components.sensor] tauron_amiplus: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 450, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 159, in _update
    self.update_configuration()
  File "/config/custom_components/tauron_amiplus/sensor.py", line 185, in update_configuration
    config = calculate_configuration(self.username, self.password, self.meter_id, 1)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 87, in calculate_configuration
    zones = json_data['dane']['zone']
KeyError: 'dane'

**Comment by PiotrMachowski** [comment]
Hi, 
Everything works for me, can you access your data on https://elicznik.tauron-dystrybucja.pl?

**Comment by Nizm0** [comment]
HM after login to web page and restart of HA everything start working. Closing.
