### ISSUE TITLE
Entities NOT AVAILABLE

### ISSUE THREAD

**Issue by Krzysztonek** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#36]
Hi @PiotrMachowski,
After the last add-on update, I noticed that both consumption and production entities are very often simply not available:

![image](https://user-images.githubusercontent.com/87784133/136785611-a310a876-35b3-4bfb-b999-3e873656a7e9.png)

To make them visible on HA dashboard I have to restart HA or at least gently reinstall the Tauron add-on. However, after that, these entities become unavailable again after some time.

I'm able to log in on the Tauron portal several times a day, where all my real data are constantly visible. When trying to see them on the Energy dashboard, they become unavailable as per the above screen.  

Will you please advise what might be the reason for such behavior?

**Comment by Krzysztonek** [comment]
...and today following errors occurred:

![image](https://user-images.githubusercontent.com/87784133/137461216-762f85dd-dce6-4bc2-864e-e58659e0c1bb.png)

**Comment by MarcinCalus** [comment]
I have same issue, connection worked only few hours and stoped working with this error.

tauron_amiplus: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 221, in _update
    self.update_configuration()
  File "/config/custom_components/tauron_amiplus/sensor.py", line 257, in update_configuration
    config = TauronAmiplusSensor.calculate_configuration(self.username, self.password, self.meter_id,
  File "/config/custom_components/tauron_amiplus/sensor.py", line 165, in calculate_configuration
    json_data = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by gorecrob** [comment]
Today after update HA, entities were not available.
I have removed integration and not possible to add it again.
![Screenshot_2021-11-10-10-43-13-064_io homeassistant companion android](https://user-images.githubusercontent.com/11458547/141089773-bf0af9f9-4c11-4d56-a293-3026f98e12b5.jpg)

**Comment by PiotrMachowski** [comment]
Fixed in `v2.1.0`
