### ISSUE TITLE
Integration not updating

### ISSUE THREAD

**Issue by MyLittleGodziak** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#53]
After restarting the HA, the integration is no longer updating - and the entities are shown as unavailable. After checking the logs, there's an error:
```
2022-05-04 14:20:29 ERROR (MainThread) [custom_components.tauron_amiplus.coordinator] Unexpected error fetching tauron_amiplus data: list indices must be integers or slices, not dict
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 20, in _async_update_data
    return await self.hass.async_add_executor_job(self._update)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 23, in _update
    return self.connector.get_raw_data()
  File "/config/custom_components/tauron_amiplus/connector.py", line 57, in get_raw_data
    data.configuration_2_days_ago = self.calculate_configuration(session, 2)
  File "/config/custom_components/tauron_amiplus/connector.py", line 97, in calculate_configuration
    zone = zones[zone_id]
TypeError: list indices must be integers or slices, not dict
```

**Comment by PiotrMachowski** [comment]
Thanks, it should be fixed in v2.1.2
