### ISSUE TITLE
Error while setting up tauron_amiplus platform for sensor

### ISSUE THREAD

**Issue by dzikus** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#7]
Since last update 2020.12.1 this issue ocured:
```
2020-12-17 15:53:17 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tauron_amiplus platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 61, in setup_platform
    dev.append(TauronAmiplusSensor(name, username, password, meter_id, generation, variable))
  File "/config/custom_components/tauron_amiplus/sensor.py", line 123, in __init__
    configuration = calculate_configuration(username, password, meter_id)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 86, in calculate_configuration
    json_data = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PiotrMachowski** [comment]
Was it working before?

**Comment by dzikus** [comment]
Yes, this is my graph of storehouse in Tauron till yesterday.
![E1123E7A-DD1C-4643-999C-A63DD7F6AE57](https://user-images.githubusercontent.com/3209066/102529767-af01ae00-40a0-11eb-9897-05996f0a03d0.jpeg)

**Comment by dzikus** [comment]
From what I noticed in ios app eLicznik, they asked to log in again today. Maybe it's just a coincidence with new release.

**Comment by PiotrMachowski** [comment]
Can you try to login using website?

**Comment by dzikus** [comment]
Without any problem.
<img width="1195" alt="Zrzut ekranu 2020-12-17 o 22 18 27" src="https://user-images.githubusercontent.com/3209066/102545013-f47ca600-40b5-11eb-857d-c79901b3aecf.png">

**Comment by maymaymay** [comment]
I gues i have the same problem, i think its from 0_118_4 --> 0_118_5, but i'm not sure:
![obraz](https://user-images.githubusercontent.com/6071653/102579815-8a87ef00-40fd-11eb-8a83-3c3414f73701.png)
![obraz](https://user-images.githubusercontent.com/6071653/102579861-ab504480-40fd-11eb-8654-0b75547bd8f0.png)

**Comment by PiotrMachowski** [comment]
It still works for me, but I haven't updated to `2020.12` yet, I will check it out after an upgrade

**Comment by maymaymay** [comment]
I think that if its tauron fault, restart HA is enough to break it.

**Comment by darth-aragoth** [comment]
Hello, I confirm, after updating to 2020.12 all entities related to amiplus are gone.

**Comment by McKenzi84** [comment]
Same here. After update everything is gone.

**Comment by karolhad** [comment]
I wasn't able to configure the integration but looks like a small fix solves the issue: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/pull/8

**Comment by PiotrMachowski** [comment]
I have added additional fixes for G12 tariff.
