### ISSUE TITLE
Encja niedostępna - problem po aktualizacji

### ISSUE THREAD

**Issue by Doliwa79** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#90]
Po aktualizacji z wersji 2.2.0 do każdej wyższej pojawia się problem. 
Pomimo poprawnych danych i pomyślny uruchomieniu dodatku encje stają się niedostępne.
Nie pomaga restart itp. 
Po powrocie do wersji 2.2.0 wszystko zaczyna działać poprawnie.
Home Assistant w wersji 2023.1

**Comment by PiotrMachowski** [comment]
Od wczoraj eLicznik padł, jak wstanie to poproszę o info z logów

**Comment by kjacek1** [comment]
Witam, mam ten sam problem 2.2.0 działa , aktualizacje wyżej już nie.

**Comment by PiotrMachowski** [comment]
@Doliwa79 bez logów nic nie zrobię

**Comment by Doliwa79** [comment]
@PiotrMachowski  mamo w logach coś takiego 
Logger: custom_components.tauron_amiplus.coordinator
Source: helpers/update_coordinator.py:201
Integration: Tauron AMIplus ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues))
First occurred: 12:37:41 (1 occurrences)
Last logged: 12:37:41

Error requesting tauron_amiplus data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by PiotrMachowski** [comment]
Teraz to nie ma sensu, bo eLicznik leży

**Comment by Doliwa79** [comment]
ok jak ruszy to wrzucę logi

**Comment by Doliwa79** [comment]
@PiotrMachowski  E licznik ruszył przesyłam info z logów
Logger: homeassistant.components.sensor
Source: runner.py:120
Integration: Sensor (documentation, issues)
First occurred: 12:05:16 (1 occurrences)
Last logged: 12:05:16

Setup of sensor platform tauron_amiplus is taking over 10 seconds.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:261
Integration: Sensor (documentation, issues)
First occurred: 12:06:06 (1 occurrences)
Last logged: 12:06:06

Setup of platform tauron_amiplus is taking longer than 60 seconds. Startup will proceed without waiting any longer.

Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.tauron_amiplus.coordinator
Source: helpers/update_coordinator.py:201
Integration: Tauron AMIplus (documentation, issues)
First occurred: 22 stycznia 2023 12:37:41 (3 occurrences)
Last logged: 12:07:45

Error requesting tauron_amiplus data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by PiotrMachowski** [comment]
@Doliwa79 jeszcze nie działa zbyt stabilnie, trzeba mu dać więcej czasu

**Comment by GregoryKowalik** [comment]
U mnie to samo. Moje logi wyglądają następująco: 
`2023-01-23 14:27:37.470 ERROR (MainThread) [custom_components.tauron_amiplus.coordinator] Unexpected error fetching tauron_amiplus data: 'tauron_importer:a322056311334_consumption'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 31, in _async_update_data
    await self.generate_statistics(data)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 37, in generate_statistics
    await statistics_updater.update_all(data)
  File "/config/custom_components/tauron_amiplus/statistics.py", line 55, in update_all
    v["sum"] = stat[s][0]["sum"]
KeyError: 'tauron_importer:a322056311334_consumption'
2023-01-23 14:27:37.476 ERROR (MainThread) [homeassistant.components.sensor] Platform tauron_amiplus does not generate unique IDs. ID tauron-A322056311334-consumption_reading already exists - ignoring sensor.tauron_amiplus_a322056311334_current_consumption_reading
2023-01-23 14:27:37.478 ERROR (MainThread) [homeassistant.components.sensor] Platform tauron_amiplus does not generate unique IDs. ID tauron-A322056311334-consumption_daily already exists - ignoring sensor.tauron_amiplus_a322056311334_daily_energy_consumption
2023-01-23 14:27:37.480 ERROR (MainThread) [homeassistant.components.sensor] Platform tauron_amiplus does not generate unique IDs. ID tauron-A322056311334-consumption_monthly already exists - ignoring sensor.tauron_amiplus_a322056311334_monthly_energy_consumption
2023-01-23 14:27:37.481 ERROR (MainThread) [homeassistant.components.sensor] Platform tauron_amiplus does not generate unique IDs. ID tauron-A322056311334-consumption_yearly already exists - ignoring sensor.tauron_amiplus_a322056311334_yearly_energy_consumption
2023-01-23 14:27:37.483 ERROR (MainThread) [homeassistant.components.sensor] Platform tauron_amiplus does not generate unique IDs. ID tauron-A322056311334-generation_reading already exists - ignoring sensor.tauron_amiplus_a322056311334_current_generation_reading
2023-01-23 14:27:37.484 ERROR (MainThread) [homeassistant.components.sensor] Platform tauron_amiplus does not generate unique IDs. ID tauron-A322056311334-generation_daily already exists - ignoring sensor.tauron_amiplus_a322056311334_daily_energy_generation
2023-01-23 14:27:37.486 ERROR (MainThread) [homeassistant.components.sensor] Platform tauron_amiplus does not generate unique IDs. ID tauron-A322056311334-generation_monthly already exists - ignoring sensor.tauron_amiplus_a322056311334_monthly_energy_generation
2023-01-23 14:27:37.488 ERROR (MainThread) [homeassistant.components.sensor] Platform tauron_amiplus does not generate unique IDs. ID tauron-A322056311334-generation_yearly already exists - ignoring sensor.tauron_amiplus_a322056311334_yearly_energy_generation`

Dodam, że korzystam teraz z konfiguracji poprzez UI

**Comment by mattPiratt** [comment]
Dla uzupełnienia informacji ja dodam że przed chwilą spróbowałem użyć modułu Tauron-AMIplus przec UI oraz wszystko działało prawidłowo. Dad za czytały się do home asystent.

**Comment by Doliwa79** [comment]
Aktualnie Tauron-AMIplus ruszył i pobrał dane.

**Comment by kjacek1** [comment]
Przesyłam moje logi najnowszej wersji:

This error originated from a custom integration.

Logger: custom_components.tauron_amiplus.coordinator
Source: components/recorder/statistics.py:2035
Integration: Tauron AMIplus (documentation, issues)
First occurred: 3:38:36 PM (2 occurrences)
Last logged: 3:38:58 PM

Unexpected error fetching tauron_amiplus data: Invalid statistic_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 31, in _async_update_data
    await self.generate_statistics(data)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 37, in generate_statistics
    await statistics_updater.update_all(data)
  File "/config/custom_components/tauron_amiplus/statistics.py", line 63, in update_all
    await self.update_stats(s, v["name"], v["sum"], v["last_stats_time"], v["zone"], raw_data[v["data_source"]])
  File "/config/custom_components/tauron_amiplus/statistics.py", line 194, in update_stats
    async_add_external_statistics(self.hass, metadata, statistic_data)
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 2035, in async_add_external_statistics
    raise HomeAssistantError("Invalid statistic_id")
homeassistant.exceptions.HomeAssistantError: Invalid statistic_id

**Comment by PiotrMachowski** [comment]
@kjacek1 masz najnowszy HA?

**Comment by kjacek1** [comment]
Home Assistant 2023.1.6
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

**Comment by PiotrMachowski** [comment]
Poszedł relase `v2.4.2`, powinien ogarnąć problemy

@GregoryKowalik nie masz czasem integracji dodanej 2x?

**Comment by kjacek1** [comment]
wersja 2.4.2 niestety nie działa
Unexpected error fetching tauron_amiplus data: Invalid statistic_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 31, in _async_update_data
    await self.generate_statistics(data)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 37, in generate_statistics
    await statistics_updater.update_all(data)
  File "/config/custom_components/tauron_amiplus/statistics.py", line 63, in update_all
    await self.update_stats(s, v["name"], v["sum"], v["last_stats_time"], v["zone"], raw_data[v["data_source"]])
  File "/config/custom_components/tauron_amiplus/statistics.py", line 194, in update_stats
    async_add_external_statistics(self.hass, metadata, statistic_data)
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 2035, in async_add_external_statistics
    raise HomeAssistantError("Invalid statistic_id")
homeassistant.exceptions.HomeAssistantError: Invalid statistic_id

**Comment by PiotrMachowski** [comment]
@kjacek1 jakie masz podane ID licznika?

**Comment by kjacek1** [comment]
takie samo jako w wersji 2.20 tj.: 
nr licznika + spacja + / + spacja + miasto (z literą "ó") +, + spacja + ulica + spacja + numer domu

**Comment by PiotrMachowski** [comment]
@kjacek1 ło... Powinieneś użyć samej pierwszej części

**Comment by kjacek1** [comment]
wszystko pięknie działa , dziękuję
nie zauważyłem - "(Punkt poboru, without address)"
wcześniej tego nie było a czytałem to wiele razy aby być pewnym że wszystko robię poprawnie

**Comment by PiotrMachowski** [comment]
@kjacek1 teraz to dodałem ;)

**Comment by GregoryKowalik** [comment]
U mnie też śmiga, wielkie dzięki :-)

**Comment by Doliwa79** [comment]
@PiotrMachowski  Niestety Tauron AMIPlus ponownie nie dział
Info z logów
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.tauron_amiplus.coordinator
Source: custom_components/tauron_amiplus/statistics.py:54
Integration: Tauron AMIplus (documentation, issues)
First occurred: 08:30:16 (3 occurrences)
Last logged: 17:01:13

Unexpected error fetching tauron_amiplus data: 'balanced_consumption'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 31, in _async_update_data
    await self.generate_statistics(data)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 37, in generate_statistics
    await statistics_updater.update_all(data)
  File "/config/custom_components/tauron_amiplus/statistics.py", line 54, in update_all
    stat = await self.get_stats(raw_data[v["data_source"]], s)
KeyError: 'balanced_consumption'

Logger: homeassistant.components.sensor
Source: runner.py:120
Integration: Sensor (documentation, issues)
First occurred: 08:30:14 (1 occurrences)
Last logged: 08:30:14

Setup of sensor platform tauron_amiplus is taking over 10 seconds.

**Comment by PiotrMachowski** [comment]
@Doliwa79 #94

**Comment by robertfili** [comment]
U mnie nie działa od 3 dni od czasu jak włączyłem Dashboard Energia
Info z logów 

Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.tauron_amiplus.coordinator
Source: custom_components/tauron_amiplus/statistics.py:54
Integration: Tauron AMIplus
First occurred: 21:49:52 (2 occurrences)
Last logged: 21:50:13

Unexpected error fetching tauron_amiplus data: 'balanced_consumption'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 31, in _async_update_data
    await self.generate_statistics(data)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 37, in generate_statistics
    await statistics_updater.update_all(data)
  File "/config/custom_components/tauron_amiplus/statistics.py", line 54, in update_all
    stat = await self.get_stats(raw_data[v["data_source"]], s)
KeyError: 'balanced_consumption'
