### ISSUE TITLE
Unexpected error fetching tauron_amiplus data: 'balanced_consumption'

### ISSUE THREAD

**Issue by skalikadam** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#94]
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.tauron_amiplus.coordinator
Source: custom_components/tauron_amiplus/statistics.py:54
Integration: Tauron AMIplus (documentation, issues)
First occurred: 12:21:44 (2 occurrences)
Last logged: 12:22:06
```
Unexpected error fetching tauron_amiplus data: 'balanced_consumption'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 31, in _async_update_data
    await self.generate_statistics(data)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 37, in generate_statistics
    await statistics_updater.update_all(data)
  File "/config/custom_components/tauron_amiplus/statistics.py", line 54, in update_all
    stat = await self.get_stats(raw_data[v["data_source"]], s)
KeyError: 'balanced_consumption'
```

**Comment by bkobylski4** [comment]
U mnie niestety również coś takiego po aktualizacji. 

Ten błąd pochodzi z niestandardowej integracji.
Logger: custom_components.tauron_amiplus.coordinator
Source: custom_components/tauron_amiplus/statistics.py:54 
Integration: Tauron AMIplus ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues)) 
First occurred: 20:25:47 (1 occurrences) 
Last logged: 20:25:47

Unexpected error fetching tauron_amiplus data: 'balanced_consumption'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 31, in _async_update_data
    await self.generate_statistics(data)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 37, in generate_statistics
    await statistics_updater.update_all(data)
  File "/config/custom_components/tauron_amiplus/statistics.py", line 54, in update_all
    stat = await self.get_stats(raw_data[v["data_source"]], s)
KeyError: 'balanced_consumption'

**Comment by PiotrMachowski** [comment]
Naprawione w `v2.4.5`
